package gestiondedatos;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author LUISA LUCIO && VALENTINA RUBIO
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    private GestorDatos gestorDatos;
    private static String algoritmoSeleccionado;
    
    public static void setAlgoritmoSeleccionado(String algoritmo) {
        algoritmoSeleccionado = algoritmo;
    }
    
    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        gestorDatos= new GestorDatos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormularioElementos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAñadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVerLista = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnDescargarArchivo = new javax.swing.JButton();
        btnMostrarEstadisticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FormularioElementos.setFont(new java.awt.Font("Perpetua Titling MT", 2, 24)); // NOI18N
        FormularioElementos.setText("Formulario elementos");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVerLista.setText("Ver lista");
        btnVerLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        btnDescargarArchivo.setText("Descargar archivo");
        btnDescargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarArchivoActionPerformed(evt);
            }
        });

        btnMostrarEstadisticas.setText("Mostrar estadisticas");
        btnMostrarEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEstadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAñadir)
                        .addGap(32, 32, 32)
                        .addComponent(btnEliminar))
                    .addComponent(btnDescargarArchivo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnVerLista)
                        .addGap(27, 27, 27)
                        .addComponent(btnOrdenar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnMostrarEstadisticas)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnEliminar)
                    .addComponent(btnVerLista)
                    .addComponent(btnOrdenar))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescargarArchivo)
                    .addComponent(btnMostrarEstadisticas))
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FormularioElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(FormularioElementos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String cantidadStr = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el dato a eliminar");
        try {
            int cantidad = Integer.parseInt(cantidadStr);
            gestorDatos.eliminarElemento(cantidad);
            javax.swing.JOptionPane.showMessageDialog(this, "El dato se ha eliminado");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListaActionPerformed
        if (algoritmoSeleccionado == null) {
            List<Integer> listadeorganizada = gestorDatos.getLista();
            JOptionPane.showMessageDialog(this, "Lista: " + listadeorganizada.toString());
        }else {
        
            
        switch (algoritmoSeleccionado) {
            case "Bubble Sort":
                gestorDatos.bubbleSort();
                break;
            case "Selection Sort":
                gestorDatos.selectionSort();
                break;
            case "Insertion Sort":
                gestorDatos.insertionSort();
                break;
            case "Merge Sort":
                gestorDatos.mergeSort();
                break;
            case "Quick Sort":
                gestorDatos.quickSort();
                break;
            case "Heap Sort":
                gestorDatos.heapSort();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Algoritmo no reconocido.");
                return;
        }
        List<Integer> listaOrdenada = gestorDatos.getLista();
        JOptionPane.showMessageDialog(this, "Lista ordenada: " + listaOrdenada.toString());
        }
    }//GEN-LAST:event_btnVerListaActionPerformed

    private void btnDescargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona un archivo de texto");

        // Solo permitir seleccionar archivos de texto
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de texto (.txt)", "txt"));

        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            String rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();            
            gestorDatos.cargarArchivo(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo.");
            }    
    }//GEN-LAST:event_btnDescargarArchivoActionPerformed

    private void btnMostrarEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEstadisticasActionPerformed
        if (algoritmoSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un algoritmo");
        return;
        }
        JOptionPane.showMessageDialog(this, gestorDatos.mostrarEstadisticas(), "Estadísticas de Ordenamiento", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMostrarEstadisticasActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        FormularioOrdenamiento formulario = new FormularioOrdenamiento();
            formulario.setVisible(true);
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String cantidadStr = javax.swing.JOptionPane.showInputDialog(this, "¿Cuántos datos desea generar?");
        try {
            int cantidad = Integer.parseInt(cantidadStr);
            gestorDatos.añadirElementosAleatorios(cantidad);
            javax.swing.JOptionPane.showMessageDialog(this, "Datos generados exitosamente.");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.");
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FormularioElementos;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnDescargarArchivo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrarEstadisticas;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerLista;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
